# Generated by Django 6.0 on 2026-01-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='examresult',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='examresult',
            name='subject',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='student_name',
            field=models.CharField(max_length=200),
        ),
    ]
