# Generated by Django 6.0 on 2026-01-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_englishquestion_mathquestion_alter_examresult_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('exam_type', models.CharField(choices=[('ENGLISH', 'English'), ('MATH', 'Math'), ('BOTH', 'English + Math')], max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
