# Generated by Django 6.0 on 2026-01-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_paymentclearance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentclearance',
            name='exam_type',
            field=models.CharField(max_length=20),
        ),
    ]
