# Generated by Django 6.0 on 2026-01-06 15:58

import exam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_paymentclearance_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentclearance',
            name='code',
            field=models.CharField(default=exam.models.generate_code, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentclearance',
            name='exam_type',
            field=models.CharField(choices=[('ENGLISH', 'English'), ('MATH', 'Math'), ('BOTH', 'Both')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentclearance',
            name='student_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
