# Generated by Django 6.0 on 2026-01-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_paymentclearance_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('exam_type', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=50)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='paymentclearance',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentclearance',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentclearance',
            name='student_email',
            field=models.EmailField(max_length=254),
        ),
    ]
