# Generated by Django 6.0 on 2026-01-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_clearancelog_paymentclearance_email_sent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentclearance',
            old_name='email_sent_at',
            new_name='last_email_at',
        ),
        migrations.RemoveField(
            model_name='clearancelog',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clearancelog',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='clearancelog',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='clearancelog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clearancelog',
            name='student_email',
            field=models.EmailField(default='unknown', max_length=254),
            preserve_default=False,
        ),
    ]
