# Generated by Django 6.0 on 2026-01-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0008_rename_email_sent_at_paymentclearance_last_email_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_email", models.EmailField(max_length=254)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[("ENGLISH", "English"), ("MATH", "Math")],
                        max_length=10,
                    ),
                ),
                ("question_ids", models.JSONField(default=list)),
                ("q_options_order", models.JSONField(default=dict)),
                ("answers", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_saved", models.DateTimeField(auto_now=True)),
                ("is_completed", models.BooleanField(default=False)),
            ],
        ),
    ]
