# Generated by Django 6.0 on 2026-01-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0009_examsession"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resume_link_expiry_seconds",
                    models.IntegerField(
                        default=3600,
                        help_text="Expiry for generated resume links in seconds",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResumeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_email", models.EmailField(max_length=254)),
                ("action", models.CharField(max_length=50)),
                ("details", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
