# Generated by Django 6.0 on 2026-01-13 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0010_examconfig_resumelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentclearance",
            name="status",
            field=models.CharField(default="PENDING", max_length=20),
        ),
        migrations.CreateModel(
            name="ClearanceActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=64)),
                ("details", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_clearance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exam.paymentclearance",
                    ),
                ),
            ],
        ),
    ]
